name: "Test PR build"

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
    # run every day at midnight
    schedule:
        - cron: '0 0 * * *'
    pull_request:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    # Use docker.io for Docker Hub if empty
    REGISTRY: ghcr.io
    # use DOCKERHUB_USERNAME as the name maybe different from the github username
    IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/arm-dependencies
    TAG: latest

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -
                name: Checkout repository
                uses: actions/checkout@v3

            -
                name: Get branch name
                id: branch-name
                uses: tj-actions/branch-names@v6

            -
                name: Set tag for PR
                run: |
                    echo "SAFETAG=${{ steps.branch-name.outputs.ref_branch }}"
                    echo "Tag will be: pr${SAFETAG%/*}"
                    echo "Branch name is ${{ steps.branch-name.outputs.ref_branch }}" # 102/merge
                    echo "Main name is ${{ steps.branch-name.outputs.default_branch }}"
                    echo "TAG=pr${SAFETAG%/*}" >> $GITHUB_ENV

            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v2
                with:
                    platforms: all
            # Workaround: https://github.com/docker/build-push-action/issues/461
            -
                name: Setup Docker buildx
                uses: docker/setup-buildx-action@v2


            # Extract metadata (tags, labels) for Docker
            # https://github.com/docker/metadata-action
            -
                name: Extract Docker metadata
                id: meta
                uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            
            # Build and push Docker image with Buildx
            # https://github.com/docker/build-push-action
            -
                name: Build and push Docker image
                id: build-and-push
                uses: docker/build-push-action@v4
                with:
                    context: .
                    push: false
                    platforms: linux/amd64,linux/arm64,linux/arm/v7
                    tags: |
                      ${{ env.IMAGE_NAME }}:${{ env.TAG }}
                    labels: ${{ steps.meta.outputs.labels }}
