name: "PR - Test Docker Build"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

# This workflow builds a docker image for every pull request, to
# confirm that the changes will still at least build even if the
# OP has not tried it themselves or configured their fork to use
# the included repos

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
        - 
            uses: actions/checkout@v4

        -
            name: Setup Docker buildx
            uses: docker/setup-buildx-action@v2.4.1

        # Build Docker image with Buildx
        # https://github.com/docker/build-push-action
        -
            name: Build amd64 Docker image
            id: build-amd64
            uses: docker/build-push-action@v4
            with:
                push: false
                context: .
                platforms: linux/amd64
                tags: automatic-ripping-machine:pr${{ github.event.number }}
        # Build Docker image with Buildx
        # https://github.com/docker/build-push-action
        -
            name: Build arm64 Docker image
            id: build-arm64
            uses: docker/build-push-action@v4
            with:
                push: false
                context: .
                platforms: linux/arm64
                tags: automatic-ripping-machine:pr${{ github.event.number }}
        # Build Docker image with Buildx
        # https://github.com/docker/build-push-action
        -
            name: Build arm64v7 Docker image
            id: build-arm64v7
            uses: docker/build-push-action@v4
            with:
                push: false
                context: .
                platforms: linux/arm/v7
                tags: automatic-ripping-machine:pr${{ github.event.number }}
